apiVersion: v1
kind: Pod
metadata:
  name: demo-app-pod
  labels:
    app: demo
spec:
  containers:
  - name: nginx-container
    image: nginx:latest
    resources:
      limits:
        cpu: "1"
        memory: "1Gi"
    volumeMounts:
    - name: app-data
      mountPath: /var/www/html

  - name: redis-container
    image: redis:latest
    resources:
      limits:
        cpu: "1"
        memory: "1Gi"

  volumes:
  - name: app-data
    hostPath:
      path: /usr/app/
      type: Directory
