apiVersion: v1
kind: Pod
metadata:
  name: demo-app-pod
  labels:
    app: demo
spec:
  containers:
  - name: demo-app
    image: gcr.io/k8s-k3s/demo:v1.0.0
    ports:
    - containerPort: 8080
    livenessProbe:
      httpGet:
        path: /health
        port: 8080
      initialDelaySeconds: 10
